blogs/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, CommentCreateView

app_name = 'blogs'

urlpatterns = [
    path('', PostListView.as_view(), name='posts'),
    path('<int:pk>/post/', PostDetailView.as_view(), name='detail'),
    path('<int:pk>/comment/', CommentCreateView.as_view(), name='comment')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('', include('users.urls')),
    path('blog/', include('blogs.urls')),
    path('shop/', include('shop.urls')),
    path('order/', include('orders.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import ShopView, ProductDetailView

app_name = 'shop'

urlpatterns = [
    path('', ShopView.as_view(), name='home'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='detail')
]

blogs/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from ckeditor_uploader.fields import RichTextUploadingField


class AutherModel(models.Model):
    full_name = models.CharField(max_length=100, verbose_name=_('full name'))
    image = models.ImageField(upload_to='auther_images/', verbose_name=_('image'))

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = _('auther')
        verbose_name_plural = _('authers')


class PostTagModel(models.Model):
    name = models.CharField(max_length=30, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('tag')
        verbose_name_plural = _('tags')


class PostModel(models.Model):
    title = models.CharField(max_length=255, verbose_name=_('title'))
    body = RichTextUploadingField(verbose_name=_('body'))
    main_image = models.ImageField(upload_to='main_images/', verbose_name=_('main image'))
    banner = models.ImageField(upload_to='post_banners/', verbose_name=_('banner'))
    auther = models.ForeignKey(AutherModel, related_name='posts', on_delete=models.RESTRICT)
    tag = models.ManyToManyField(PostTagModel, related_name='posts', verbose_name=_('tag'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))



    def __str__(self):
        return f"{self.title[:100]} ..."

    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')


class CommentModel(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('name'))
    email = models.EmailField(verbose_name=_('email'))
    phone = models.CharField(max_length=13, verbose_name=_('phone'))
    comment = models.TextField(verbose_name=_('comment'))
    post = models.ForeignKey(PostModel, on_delete=models.CASCADE, related_name='comments', verbose_name=_('post'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return f"{self.name}\n{self.email}\n{self.phone}\n{self.comment}"

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')

shop/models.py
import decimal

from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from ckeditor_uploader.fields import RichTextUploadingField


class CategoryModel(models.Model):
    name = models.CharField(max_length=60, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class ProductTagModel(models.Model):
    name = models.CharField(max_length=60, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'


class ProductModel(models.Model):
    title = models.CharField(max_length=60, verbose_name=_('title'))
    short_description = models.CharField(max_length=255, verbose_name=_('short description'))
    long_description = RichTextUploadingField(verbose_name=_('long description'))
    price = models.FloatField(verbose_name=_('price'))
    discount = models.PositiveSmallIntegerField(default=0, verbose_name=_('discount'))
    main_image = models.ImageField(upload_to='products/', verbose_name=_('main image'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))
    category = models.ForeignKey(
        CategoryModel,
        on_delete=models.RESTRICT,
        related_name='products',
        verbose_name=_('category')
    )
    tags = models.ManyToManyField(
        ProductTagModel,
        related_name='products',
        verbose_name=_('tags')
    )

    def get_price(self):
        if self.discount:
            return ((100 - self.discount) / 100) * self.price
        return self.price

    def is_discount(self):
        return bool(self.discount)

    def new(self):
        return (timezone.now() - self.created_at).days <= 5

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'

blogs/forms.py
from django import forms
from .models import CommentModel

class CommentModelForm(forms.ModelForm):

    class Meta:
        model = CommentModel
        exclude = ['created_at', 'post']

blogs/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView
from .models import PostModel
from .forms import CommentModelForm


class PostListView(ListView):
    template_name = 'blog.html'

    def get_queryset(self):
        qs = PostModel.objects.order_by('-id')
        tag = self.request.GET.get('tag')
        if tag:
            qs = qs.filter(tag__name=tag)
        return qs


class PostDetailView(DetailView):
    model = PostModel
    template_name = 'blog-detail.html'


class CommentCreateView(CreateView):
    form_class = CommentModelForm

    def form_valid(self, form):
        print(form.instance)
        form.instance.post = get_object_or_404(PostModel, pk=self.kwargs.get('pk'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blogs:detail', kwargs={'pk':self.kwargs.get('pk')})

shop/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import ProductModel, CategoryModel, ProductTagModel


class ShopView(ListView):
    template_name = 'shop.html'
    paginate_by = 3

    def get_queryset(self):
        qs = ProductModel.objects.all()

        search = self.request.GET.get('search')
        if search:
            qs = qs.filter(title__icontains=search)

        cat = self.request.GET.get('cat')
        if cat:
            qs = qs.filter(category_id=cat)

        tag = self.request.GET.get('tag')
        if tag:
            qs = qs.filter(tags=tag)

        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data()
        data['categories'] = CategoryModel.objects.all()
        data['tags'] = ProductTagModel.objects.all()
        return data


class ProductDetailView(DetailView):
    model = ProductModel
    template_name = 'shop-details.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data()
        data['products'] = ProductModel.objects.all().exclude(id=self.object.pk)[:4]
        return data

templates/blog-details.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}

    <!-- Blog Details Hero Begin -->
    <section class="blog-hero spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-9 text-center">
                    <div class="blog__hero__text">
                        <h2>{{ object.title }}</h2>
                        <ul>
                            <li>By {{ object.auther.full_name }}</li>
                            <li>{{ object.created_at|date:"F d, Y" }}</li>
                            {% if object.comments.values %}
                                <li>{{ object.comments.values.count }} Comments</li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Hero End -->

    <!-- Blog Details Section Begin -->
    <section class="blog-details spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-12">
                    <div class="blog__details__pic">
                        <img src="{{ object.banner.url }}" alt="{{ object.title }}">
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="blog__details__content">
                        <div class="blog__details__share">
                            <span>share</span>
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" class="youtube"><i class="fa fa-youtube-play"></i></a></li>
                                <li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                        <div class="blog__details__text">
                            {{ object.body|safe }}
                        </div>
                        <div class="blog__details__quote">
                            <i class="fa fa-quote-left"></i>
                            <p>“When designing an advertisement for a particular product many things should be
                                researched like where it should be displayed.”</p>
                            <h6>_ John Smith _</h6>
                        </div>
                        <div class="blog__details__option">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__author">
                                        <div class="blog__details__author__pic">
                                            <img src="{{ object.auther.image.url }}"
                                                 alt="{{ object.auther.full_name }}">
                                        </div>
                                        <div class="blog__details__author__text">
                                            <h5>{{ object.auther.full_name }}</h5>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__tags">
                                        {% for tag in object.tag.values %}
                                            <a href="{% url 'blogs:posts' %}?tag={{ tag.name }}">#{{ tag.name }}</a>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="blog__details__btns">
                            <div class="row">
                                {% if object.get_next_by_created_at %}
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <a href="{% url 'blogs:detail' pk=object.get_next_by_created_at.pk %}"
                                           class="blog__details__btns__item">
                                            <p><span class="arrow_left"></span> Previous Pod</p>
                                            <h5>{{ object.get_next_by_created_at.title }}</h5>
                                        </a>
                                    </div>
                                {% endif %}
                                {% if object.get_previous_by_created_at %}
                                    <div class="col-lg-6 col-md-6 col-sm-6 {% if not object.get_next_by_created_at %}offset-6{% endif %}">
                                        <a href="{% url 'blogs:detail' pk=object.get_previous_by_created_at.pk %}"
                                           class="blog__details__btns__item blog__details__btns__item--next">
                                            <p>Next Pod <span class="arrow_right"></span></p>
                                            <h5>{{ object.get_previous_by_created_at.title }}</h5>
                                        </a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="container">
                            {% for comment in object.comments.values %}
                                <div class="row mb-3">
                                    <div class="col-6"><strong>{{ comment.name }}</strong></div>
                                    <div class="col-6 text-right">{{ comment.created_at|timesince }}</div>
                                    <div class="col-12 mt-2">
                                        <p>
                                            {{ comment.comment }}
                                        </p>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="blog__details__comment">
                            <h4>Leave A Comment</h4>
                            <form action="{% url 'blogs:comment' pk=object.pk %}" method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-4 col-md-4">
                                        <input name="name" type="text" placeholder="Name">
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        <input name="email" type="text" placeholder="Email">
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        <input name="phone" type="text" placeholder="Phone">
                                    </div>
                                    <div class="col-lg-12 text-center">
                                        <textarea name="comment" placeholder="Comment"></textarea>
                                        <button type="submit" class="site-btn">Post Comment</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Section End -->

{% endblock %}

templates/blog.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-blog set-bg" data-setbg="{% static 'img/breadcrumb-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    {% if request.GET %}
                        <h2>#{{ request.GET.tag }}</h2>
                    {% else %}
                        <h2>Our Blog</h2>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Blog Section Begin -->
    <section class="blog spad">
        <div class="container">
            <div class="row">
                {% for post in object_list %}
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="blog__item">
                            <div class="blog__item__pic set-bg" data-setbg="{{ post.main_image.url }}"></div>
                            <div class="blog__item__text">
                                <span><img src="{% static 'img/icon/calendar.png' %}" alt=""> {{ post.created_at|date:"d F Y" }}</span>
                                <h5>{{ post.title|title|truncatewords:"10" }}</h5>
                                <a href="{% url 'blogs:detail' post.pk %}">Read More</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Blog Section End -->
{% endblock %}

templates/contact.html
{% extends 'layouts/base.html' %}

{% block content %}
    <!-- Map Begin -->
    <div class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d111551.9926412813!2d-90.27317134641879!3d38.606612219170856!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54eab584e432360b%3A0x1c3bb99243deb742!2sUnited%20States!5e0!3m2!1sen!2sbd!4v1597926938024!5m2!1sen!2sbd" height="500" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    </div>
    <!-- Map End -->

    <!-- Contact Section Begin -->
    <section class="contact spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="contact__text">
                        <div class="section-title">
                            <span>Information</span>
                            <h2>Contact Us</h2>
                            <p>As you might expect of a company that began as a high-end interiors contractor, we pay
                                strict attention.</p>
                        </div>
                        <ul>
                            <li>
                                <h4>America</h4>
                                <p>195 E Parker Square Dr, Parker, CO 801 <br />+43 982-314-0958</p>
                            </li>
                            <li>
                                <h4>France</h4>
                                <p>109 Avenue Léon, 63 Clermont-Ferrand <br />+12 345-423-9893</p>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="contact__form">
                        <form action="#" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-6">
                                    <input name="name" type="text" placeholder="Name">
                                </div>
                                <div class="col-lg-6">
                                    <input name="email" type="email" placeholder="Email">
                                </div>
                                <div class="col-lg-12">
                                    <textarea name="massage" placeholder="Message"></textarea>
                                    <button type="submit" class="site-btn">Send Message</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact Section End -->
{% endblock %}

templates/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

templates/product_item.html
{% load static %}
<div class="product__item sale">
    <div class="product__item__pic set-bg"
         data-setbg="{{ product.main_image.url }}">
        {% if product.is_discount %}
            <span class="label">Sale</span>
        {% endif %}
        {% if product.new %}
            <span class="label new {% if product.is_discount %}new-mt{% endif %}">New</span>
        {% endif %}
        <ul class="product__hover">
            <li><a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
            </li>
            <li><a href="{% url 'shop:detail' pk=product.pk %}"><img src="{% static 'img/icon/search.png' %}"
                                                                     alt=""></a>
            </li>
        </ul>
    </div>
    <div class="product__item__text">
        <h6>{{ product.title }}</h6>
        <a href="#" class="add-cart">+ Add To Cart</a>
        <div class="rating">
            <i class="fa fa-star"></i>
            <i class="fa fa-star"></i>
            <i class="fa fa-star"></i>
            <i class="fa fa-star"></i>
            <i class="fa fa-star-o"></i>
        </div>
        <h5>${{ product.get_price }} {% if product.is_discount %}
            <del class="text-secondary">{{ product.price }}</del> {% endif %}</h5>
        <div class="product__color__select">
            <label for="pc-16">
                <input type="radio" id="pc-16">
            </label>
            <label class="active black" for="pc-17">
                <input type="radio" id="pc-17">
            </label>
            <label class="grey" for="pc-18">
                <input type="radio" id="pc-18">
            </label>
        </div>
    </div>
</div>

templates/shop_sidebar.html
{% load static %}
<div class="shop__sidebar">
    <div class="shop__sidebar__search">
        <form action="{% url 'shop:home' %}" , method="GET">
            <input name="search" value="{{ request.GET.search }}" type="text" placeholder="Search...">
            <button type="submit"><span class="icon_search"></span></button>
        </form>
    </div>
    <div class="shop__sidebar__accordion">
        <div class="accordion" id="accordionExample">
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseOne">Categories</a>
                </div>
                <div id="collapseOne" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__categories">
                            <ul class="nice-scroll">
                                <!-- {% for cat in categories %}
                                    <li><a onclick="addUrlParameter('cat', {{ cat.pk }})" style="cursor: pointer"
                                           class="{% if request.GET.cat == cat.pk|stringformat:'i' %}text-dark{% endif %}">{{ cat.name }}
                                        ({{ cat.products.count }})</a></li>
                                {% endfor %} -->
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseTwo">Branding</a>
                </div>
                <div id="collapseTwo" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__brand">
                            <ul>
                                <li><a href="#">Louis Vuitton</a></li>
                                <li><a href="#">Chanel</a></li>
                                <li><a href="#">Hermes</a></li>
                                <li><a href="#">Gucci</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseThree">Filter Price</a>
                </div>
                <div id="collapseThree" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__price">
                            <ul>
                                <li><a href="#">$0.00 - $50.00</a></li>
                                <li><a href="#">$50.00 - $100.00</a></li>
                                <li><a href="#">$100.00 - $150.00</a></li>
                                <li><a href="#">$150.00 - $200.00</a></li>
                                <li><a href="#">$200.00 - $250.00</a></li>
                                <li><a href="#">250.00+</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseFour">Size</a>
                </div>
                <div id="collapseFour" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__size">
                            <label for="xs">xs
                                <input type="radio" id="xs">
                            </label>
                            <label for="sm">s
                                <input type="radio" id="sm">
                            </label>
                            <label for="md">m
                                <input type="radio" id="md">
                            </label>
                            <label for="xl">xl
                                <input type="radio" id="xl">
                            </label>
                            <label for="2xl">2xl
                                <input type="radio" id="2xl">
                            </label>
                            <label for="xxl">xxl
                                <input type="radio" id="xxl">
                            </label>
                            <label for="3xl">3xl
                                <input type="radio" id="3xl">
                            </label>
                            <label for="4xl">4xl
                                <input type="radio" id="4xl">
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseFive">Colors</a>
                </div>
                <div id="collapseFive" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__color">
                            <label class="c-1" for="sp-1">
                                <input type="radio" id="sp-1">
                            </label>
                            <label class="c-2" for="sp-2">
                                <input type="radio" id="sp-2">
                            </label>
                            <label class="c-3" for="sp-3">
                                <input type="radio" id="sp-3">
                            </label>
                            <label class="c-4" for="sp-4">
                                <input type="radio" id="sp-4">
                            </label>
                            <label class="c-5" for="sp-5">
                                <input type="radio" id="sp-5">
                            </label>
                            <label class="c-6" for="sp-6">
                                <input type="radio" id="sp-6">
                            </label>
                            <label class="c-7" for="sp-7">
                                <input type="radio" id="sp-7">
                            </label>
                            <label class="c-8" for="sp-8">
                                <input type="radio" id="sp-8">
                            </label>
                            <label class="c-9" for="sp-9">
                                <input type="radio" id="sp-9">
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseSix">Tags</a>
                </div>
                <div id="collapseSix" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__tags">
                            <!-- {% for tag in tags %}
                                <a href="?tag={{ tag.pk }}" style="{% if request.GET.tag == tag.pk|stringformat:'i' %}background-color: #000; color: #fff; {% endif %}" >#{{ tag.name }}</a>
                            {% endfor %} -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>